---
appearance:
  prism:
    theme: PRISM
jenkins:
  agentProtocols:
    - JNLP4-connect
    - Ping
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  globalNodeProperties:
    - envVars:
        env:
          - key: NAME
            value: TEST
  labelAtoms:
    - name: built-in
  markupFormatter: plainText
  mode: NORMAL
  myViewsTabBar: standard
  nodeMonitors:
    - architecture
    - clock
    - diskSpace:
        freeSpaceThreshold: 1GiB
        freeSpaceWarningThreshold: 2GiB
    - swapSpace
    - tmpSpace:
        freeSpaceThreshold: 1GiB
        freeSpaceWarningThreshold: 2GiB
    - responseTime
  numExecutors: 2
  primaryView:
    all:
      name: all
  projectNamingStrategy: standard
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: chocolateen
          name: Hugo
          password: ${USER_CHOCOLATEEN_PASSWORD}
        - id: vaugie_g
          name: Garance
          password: ${USER_VAUGIE_G_PASSWORD}
        - id: i_dont_know
          name: Jeremy
          password: ${USER_I_DONT_KNOW_PASSWORD}
        - id: nasso
          name: Nassim
          password: ${USER_NASSO_PASSWORD}
  slaveAgentPort: 50000
  systemMessage: Welcome to the Chocolatine-Powered Marvin Jenkins Instance.
  updateCenter:
    sites:
      - id: default
        url: https://updates.jenkins.io/update-center.json
  views:
    - all:
        name: all
  viewsTabBar: standard
jobs:
  - file: /var/jenkins_home/job_dsl.groovy
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
tool:
  mavenGlobalConfig:
    globalSettingsProvider: standard
    settingsProvider: standard
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
      - jobBuildDiscarder
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: file
  location:
    adminAddress: address not configured yet <nobody@nowhere>
  pollSCM:
    pollingThreadCount: 10