name: action
run-name: ${{ github.actor }} asking for main action
on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

jobs:
  check_program_compilation:
    name: check_program_compilation
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

      - name: Checkout GH repository
        uses: actions/checkout@v4
        with:
          repository: ''

      - name: Launch project
        run: docker compose up --build -d

      - name: Stop project
        run: docker compose down

  push_to_mirror:
    name: push_to_mirror
    runs-on: ubuntu-latest
    needs: [check_program_compilation]
    if: github.event_name == 'push'
    steps:

      - name: Checkout GH repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ vars.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}